[workspace]
resolver = "2"
members = ["crates/awake-core", "crates/awake-cli", "apps/awake-tray/src-tauri"]
default-members = ["crates/awake-core", "crates/awake-cli"]

[workspace.package]
version = "0.1.1"
edition = "2021"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/nolliebigspin/awake"
homepage = "https://github.com/nolliebigspin/awake"
authors = ["Alec Winter"]

[workspace.dependencies]
awake-core = { path = "crates/awake-core", version = "0.1.1" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
strip = true
